---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentorchestrators.regulens.ai
  labels:
    app.kubernetes.io/name: regulens
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
spec:
  group: regulens.ai
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                maximum: 100
                default: 3
                description: "Number of agent orchestrator replicas"
              image:
                type: string
                description: "Container image for agent orchestrator"
                default: "regulens/agent-orchestrator:latest"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "500m"
                      memory:
                        type: string
                        default: "1Gi"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "2"
                      memory:
                        type: string
                        default: "4Gi"
              config:
                type: object
                properties:
                  logLevel:
                    type: string
                    enum: ["DEBUG", "INFO", "WARN", "ERROR"]
                    default: "INFO"
                  enableMetrics:
                    type: boolean
                    default: true
                  maxConcurrentTasks:
                    type: integer
                    minimum: 1
                    maximum: 1000
                    default: 100
                  taskTimeoutSeconds:
                    type: integer
                    minimum: 30
                    maximum: 3600
                    default: 300
                  enableCircuitBreaker:
                    type: boolean
                    default: true
                  circuitBreakerThreshold:
                    type: integer
                    minimum: 1
                    maximum: 20
                    default: 5
              agents:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                      enum: ["compliance", "audit", "regulatory", "risk"]
                    enabled:
                      type: boolean
                      default: true
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 50
                      default: 2
                    priority:
                      type: string
                      enum: ["low", "medium", "high", "critical"]
                      default: "medium"
              database:
                type: object
                properties:
                  host:
                    type: string
                  port:
                    type: integer
                    default: 5432
                  name:
                    type: string
                    default: "regulens_compliance"
                  user:
                    type: string
                  passwordSecret:
                    type: string
                  sslMode:
                    type: string
                    enum: ["disable", "require", "verify-ca", "verify-full"]
                    default: "require"
              redis:
                type: object
                properties:
                  host:
                    type: string
                  port:
                    type: integer
                    default: 6379
                  passwordSecret:
                    type: string
                  database:
                    type: integer
                    default: 0
              monitoring:
                type: object
                properties:
                  prometheusEnabled:
                    type: boolean
                    default: true
                  grafanaDashboardEnabled:
                    type: boolean
                    default: true
                  alertManagerEnabled:
                    type: boolean
                    default: true
            required:
            - image
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Scaling"]
              replicas:
                type: integer
              availableReplicas:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              lastUpdateTime:
                type: string
                format: date-time
              version:
                type: string
              agents:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    status:
                      type: string
                      enum: ["Running", "Pending", "Failed", "Unknown"]
                    replicas:
                      type: integer
                    lastHealthCheck:
                      type: string
                      format: date-time
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: agentorchestrators
    singular: agentorchestrator
    kind: AgentOrchestrator
    shortNames:
    - ao
    - aos
