---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: complianceagents.regulens.ai
  labels:
    app.kubernetes.io/name: regulens
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: kustomize
spec:
  group: regulens.ai
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              type:
                type: string
                enum: ["transaction_guardian", "audit_intelligence", "regulatory_assessor", "risk_analyzer"]
                description: "Type of compliance agent"
              replicas:
                type: integer
                minimum: 1
                maximum: 50
                default: 2
                description: "Number of agent replicas"
              image:
                type: string
                description: "Container image for compliance agent"
                default: "regulens/compliance-agent:latest"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "250m"
                      memory:
                        type: string
                        default: "512Mi"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "1"
                      memory:
                        type: string
                        default: "2Gi"
              config:
                type: object
                properties:
                  logLevel:
                    type: string
                    enum: ["DEBUG", "INFO", "WARN", "ERROR"]
                    default: "INFO"
                  enableMetrics:
                    type: boolean
                    default: true
                  processingTimeoutSeconds:
                    type: integer
                    minimum: 30
                    maximum: 1800
                    default: 300
                  maxConcurrentRequests:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 10
                  enableLLMIntegration:
                    type: boolean
                    default: true
                  llmProvider:
                    type: string
                    enum: ["openai", "anthropic", "local"]
                    default: "openai"
                  enableEmbeddings:
                    type: boolean
                    default: true
                  enableCaseBasedReasoning:
                    type: boolean
                    default: true
                  riskThreshold:
                    type: number
                    minimum: 0.0
                    maximum: 1.0
                    default: 0.7
                  confidenceThreshold:
                    type: number
                    minimum: 0.0
                    maximum: 1.0
                    default: 0.8
              llmConfig:
                type: object
                properties:
                  openaiApiKeySecret:
                    type: string
                  openaiModel:
                    type: string
                    default: "gpt-4"
                  anthropicApiKeySecret:
                    type: string
                  anthropicModel:
                    type: string
                    default: "claude-3-sonnet-20240229"
                  localLLMEndpoint:
                    type: string
                  temperature:
                    type: number
                    minimum: 0.0
                    maximum: 2.0
                    default: 0.1
                  maxTokens:
                    type: integer
                    minimum: 100
                    maximum: 32768
                    default: 4096
              regulatorySources:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                      enum: ["sec", "fca", "ecb", "esma", "fed"]
                    enabled:
                      type: boolean
                      default: true
                    pollingIntervalMinutes:
                      type: integer
                      minimum: 5
                      maximum: 1440
                      default: 60
                    priority:
                      type: string
                      enum: ["low", "medium", "high"]
                      default: "medium"
              scaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  minReplicas:
                    type: integer
                    minimum: 1
                    maximum: 10
                    default: 1
                  maxReplicas:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 10
                  targetCPUUtilizationPercentage:
                    type: integer
                    minimum: 10
                    maximum: 90
                    default: 70
                  targetMemoryUtilizationPercentage:
                    type: integer
                    minimum: 10
                    maximum: 90
                    default: 80
                  scaleUpThreshold:
                    type: integer
                    minimum: 1
                    maximum: 1000
                    default: 50
                  scaleDownThreshold:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 20
              monitoring:
                type: object
                properties:
                  prometheusEnabled:
                    type: boolean
                    default: true
                  customMetrics:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                          enum: ["counter", "gauge", "histogram"]
                        description:
                          type: string
            required:
            - type
            - image
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed", "Scaling", "Updating"]
              replicas:
                type: integer
              availableReplicas:
                type: integer
              readyReplicas:
                type: integer
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              lastUpdateTime:
                type: string
                format: date-time
              version:
                type: string
              performanceMetrics:
                type: object
                properties:
                  requestsProcessed:
                    type: integer
                  averageProcessingTime:
                    type: number
                  errorRate:
                    type: number
                  llmTokensUsed:
                    type: integer
                  cacheHitRate:
                    type: number
              regulatorySources:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    lastFetch:
                      type: string
                      format: date-time
                    documentsFetched:
                      type: integer
                    status:
                      type: string
                      enum: ["Healthy", "Degraded", "Failed"]
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: complianceagents
    singular: complianceagent
    kind: ComplianceAgent
    shortNames:
    - ca
    - cas
